// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS4RL0mJQIMVTDLkZZChvmVgUgoLGpqqg',
    appId: '1:1055252011970:web:2a61b6e65d05a1f917145b',
    messagingSenderId: '1055252011970',
    projectId: 'quickqueue-rw',
    authDomain: 'quickqueue-rw.firebaseapp.com',
    storageBucket: 'quickqueue-rw.firebasestorage.app',
    measurementId: 'G-SL5E6KHZNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB58_2jooWXPyGLHYLT08QJo9eOynvvwMY',
    appId: '1:1055252011970:android:b3f1f1e2370a846d17145b',
    messagingSenderId: '1055252011970',
    projectId: 'quickqueue-rw',
    storageBucket: 'quickqueue-rw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCffGfxwjLTekm2qas91E8V0-cZTK_H_Wk',
    appId: '1:1055252011970:ios:7844890f3587e85817145b',
    messagingSenderId: '1055252011970',
    projectId: 'quickqueue-rw',
    storageBucket: 'quickqueue-rw.firebasestorage.app',
    iosClientId: '1055252011970-s7rrrqbh7v2hunaldj313329isjd1tvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickqueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCffGfxwjLTekm2qas91E8V0-cZTK_H_Wk',
    appId: '1:1055252011970:ios:7844890f3587e85817145b',
    messagingSenderId: '1055252011970',
    projectId: 'quickqueue-rw',
    storageBucket: 'quickqueue-rw.firebasestorage.app',
    iosClientId: '1055252011970-s7rrrqbh7v2hunaldj313329isjd1tvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickqueue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS4RL0mJQIMVTDLkZZChvmVgUgoLGpqqg',
    appId: '1:1055252011970:web:a4fb4e721d91223617145b',
    messagingSenderId: '1055252011970',
    projectId: 'quickqueue-rw',
    authDomain: 'quickqueue-rw.firebaseapp.com',
    storageBucket: 'quickqueue-rw.firebasestorage.app',
    measurementId: 'G-ZF3FG9FXEG',
  );
}
